version: '3'

services: 
    consulserver01:
        image: consul:1.10
        container_name: consulserver01
        hostname: consulserver01
        command: ['tail','-f','/dev/null']
        tty: true
        volumes:
          - ./servers/server01:/etc/consul.d
        ports:
          - "8500:8500"

        networks:
          - consul-net

    consulserver02:
        image: consul:1.10
        container_name: consulserver02
        hostname: consulserver02
        command: ['tail','-f','/dev/null']
        tty: true
        volumes:
          - ./servers/server02:/etc/consul.d

        networks:
          - consul-net

    consulserver03:
        image: consul:1.10
        container_name: consulserver03
        hostname: consulserver03
        command: ['tail','-f','/dev/null']
        tty: true
        volumes:
          - ./servers/server03:/etc/consul.d

        networks:
          - consul-net


    consulclient01:
        image: consul:1.10
        container_name: consulclient01
        hostname: consulclient01
        command: ['tail','-f','/dev/null']
        tty: true
        volumes:
          - ./clients/consul01:/etc/consul.d
        networks:
          - consul-net

          
    consulclient02:
        image: consul:1.10
        container_name: consulclient02
        hostname: consulclient02
        command: ['tail','-f','/dev/null']
        tty: true
        volumes:
          - ./clients/consul02:/etc/consul.d
        networks:
          - consul-net


networks: 
    consul-net:
        name: consul-net
        driver: bridge     